'use client';

import { Mail } from 'lucide-react';
import { ActivePage } from '@/lib/types';

export default function FooterIE({ onNavigate }: { onNavigate: (page: ActivePage, subjectTitle?: string) => void }) {
  const links: [string, ActivePage][] = [['Home', 'home'], ['Curriculum', 'curriculum'], ['Mock Papers', 'mock-papers'], ['Predicted Papers', 'predicted-papers'], ['About Us', 'about'], ['Blogs', 'blogs'], ['Test Preparation', 'test-prep'], ['Free Trial Booking', 'trial']];
  return <footer className="bg-soft-gray border-t border-outline-variant/20 w-full mt-12"><div className="max-w-max-width mx-auto px-margin-mobile md:px-margin-desktop py-16 grid grid-cols-1 md:grid-cols-4 gap-12"><div><button onClick={() => onNavigate('home')} className="flex items-center cursor-pointer"><img src="https://lh3.googleusercontent.com/aida-public/AB6AXuC2yGxrC4Kei9fXSf6ye1GNFumbjoh74eclxhyJXD0vhlpt-qjKZp73AfFIIibakj1gEbmNoJ6qQLdYSr95j_EUf5iaNd9Z0NMrkoWeMC8bxDz0o2lFwDBG3obFf_nj5AWi45pYBcZEKVEJ3deavLesEieFE89BhkaMlE6iQQ3FCSWysyXYrsEGu1ko8RAYQG4-iBKirBzyiTDVK0lKb__9V9dOHgreWgJzvYIo44hEWv5pC5Hw-_-shU7Arw_B1_0x0-U" alt="Math Make Smart Logo" className="h-10 w-auto object-contain" /></button><p className="mt-6 text-on-surface-variant">Professional mathematics tutoring for students across Ireland.</p></div><div><h4 className="mb-6 uppercase">Explore</h4>{links.map(([label, page]) => <button key={page} onClick={() => onNavigate(page)} className="block mb-4 hover:text-primary text-left">{label}</button>)}</div><div><h4 className="mb-6 uppercase">Legal</h4><button onClick={() => onNavigate('privacy')} className="block mb-4 hover:text-primary">Privacy Policy</button><button onClick={() => onNavigate('refund')} className="block hover:text-primary">Refund Policy</button></div><div><h4 className="mb-6 uppercase">Ireland Support</h4><p className="text-on-surface-variant">Specialist tutors aligned with Ireland&apos;s curriculum and assessments.</p><a href="mailto:info@mathmakesmart.com" className="mt-5 flex items-center gap-2 text-royal-purple"><Mail className="w-4 h-4" />info@mathmakesmart.com</a></div></div><div className="border-t border-surface-container py-8 text-center text-on-surface-variant text-xs">© 2026 Math Make Smart LLC. Supporting students across Ireland.</div></footer>;
}
