'use client';

import { Mail } from 'lucide-react';
import { ActivePage } from '@/lib/types';

interface FooterProps { onNavigate: (page: ActivePage, subjectTitle?: string) => void; }

export default function FooterAU({ onNavigate }: FooterProps) {
  const links: [string, ActivePage][] = [['Home', 'home'], ['Curriculum', 'curriculum'], ['Mock Papers', 'mock-papers'], ['Predicted Papers', 'predicted-papers'], ['About Us', 'about'], ['Blogs', 'blogs'], ['Test Preparation', 'test-prep'], ['Free Trial Booking', 'trial']];
  return <footer className="bg-soft-gray border-t border-outline-variant/20 w-full mt-12"><div className="max-w-max-width mx-auto px-margin-mobile md:px-margin-desktop py-16 grid grid-cols-1 md:grid-cols-4 gap-12"><div className="space-y-6"><button onClick={() => onNavigate('home')} className="flex items-center cursor-pointer"><img src="https://lh3.googleusercontent.com/aida-public/AB6AXuC2yGxrC4Kei9fXSf6ye1GNFumbjoh74eclxhyJXD0vhlpt-qjKZp73AfFIIibakj1gEbmNoJ6qQLdYSr95j_EUf5iaNd9Z0NMrkoWeMC8bxDz0o2lFwDBG3obFf_nj5AWi45pYBcZEKVEJ3deavLesEieFE89BhkaMlE6iQQ3FCSWysyXYrsEGu1ko8RAYQG4-iBKirBzyiTDVK0lKb__9V9dOHgreWgJzvYIo44hEWv5pC5Hw-_-shU7Arw_B1_0x0-U" alt="Math Make Smart Logo" className="h-10 w-auto object-contain" /></button><p className="font-body-md text-body-md text-on-surface-variant leading-relaxed">Professional mathematics tutoring for students across Australia. Patient, structured, and effective.</p></div><FooterExplore links={links} onNavigate={onNavigate} /><FooterLegal onNavigate={onNavigate} /><FooterSupport countryName="Australia" /></div><FooterCopyright countryName="Australia" /></footer>;
}

function FooterExplore({ links, onNavigate }: { links: [string, ActivePage][] } & FooterProps) { return <div><h4 className="font-label-md text-label-md text-charcoal uppercase tracking-wider mb-6">Explore</h4><ul className="space-y-4 font-body-md text-body-md text-on-surface-variant">{links.map(([label, page]) => <li key={page}><button onClick={() => onNavigate(page)} className="hover:text-primary transition-colors cursor-pointer text-left">{label}</button></li>)}</ul></div>; }
function FooterLegal({ onNavigate }: FooterProps) { return <div><h4 className="font-label-md text-label-md text-charcoal uppercase tracking-wider mb-6">Legal</h4><ul className="space-y-4 font-body-md text-body-md text-on-surface-variant"><li><button onClick={() => onNavigate('privacy')} className="hover:text-primary transition-colors cursor-pointer text-left">Privacy Policy</button></li><li><button onClick={() => onNavigate('refund')} className="hover:text-primary transition-colors cursor-pointer text-left">Refund Policy</button></li><li><a href="#" className="hover:text-primary transition-colors">Terms of Service</a></li><li><a href="#" className="hover:text-primary transition-colors">Cookie Policy</a></li></ul></div>; }
function FooterSupport({ countryName }: { countryName: string }) { return <div><h4 className="font-label-md text-label-md text-charcoal uppercase tracking-wider mb-6">{countryName} Support</h4><p className="font-body-md text-body-md text-on-surface-variant text-sm">Specialist tutors aligned with {countryName}&apos;s curriculum and assessments.</p><a href="mailto:info@mathmakesmart.com" className="mt-5 flex items-center gap-2 text-royal-purple font-medium text-sm"><Mail className="w-4 h-4" />info@mathmakesmart.com</a></div>; }
function FooterCopyright({ countryName }: { countryName: string }) { return <div className="border-t border-surface-container py-8 px-margin-mobile md:px-margin-desktop"><div className="max-w-max-width mx-auto flex flex-col md:flex-row justify-between items-center gap-4 text-on-surface-variant text-xs"><p>© 2026 Math Make Smart LLC. All rights reserved.</p><span>Supporting students across {countryName}</span></div></div>; }
